### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by roozbehes** [Nakheem/Data301#2]
Hi

- [x] you should clearly explain what your research question is

- [x] for each block of code EDA or analysis you should explain what you are looking for and how that helps you answer your questions 

- [x] overall the milestone 2 file is very unorganized and should be cleaned up 

- [x] do more analysis and more EDA, one chart is not enough
